### ISSUE TITLE
use random.SystemRandom() or os.urandom for secret generation

### ISSUE THREAD

**Issue by ghost** [soslan/passgen#3]
uh yeah, using a pseudorandom number generator (PRNG) for secrets (passwords) is not acceptable, if your going to keep this published on pypi, I must strongly encourage the heedence of the documented prng module https://docs.python.org/2/library/random.html

In that random.SystemRandom or os.urandom be used to choose the random value.

> Warning
> 
> The pseudo-random generators of this module should not be used for security purposes. Use os.urandom() or SystemRandom if you require a cryptographically secure pseudo-random number generator. 

The premise of PRNG is that the results are seeded and entirely reproducible, a trivial replay attack can produce the passwords generated here.

**Comment by soslan** [comment]
I will address this issue as soon as possible. Thanks.

**Comment by soslan** [comment]
Done in 406e881473d14c721b6cc2b66285c9243dfdb8de.
